import { Inter } from "next/font/google";
import "./globals.css";
import { BrowserRouter } from "react-router-dom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Joe Nadiv Concepts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.4.0/uicons-bold-rounded/css/uicons-bold-rounded.css'></link>
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.4.0/uicons-regular-rounded/css/uicons-regular-rounded.css'></link>
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.4.0/uicons-bold-straight/css/uicons-bold-straight.css'></link>
      </head>
        <body className={inter.className}>{children}</body>
    </html>
  );
}
